version: '2'

services:
  app:
    image: jekyll/jekyll
    command: sh -c 'update-ca-certificates && jekyll build --watch --future --drafts'
    volumes:
      - ./:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle
      - ./httpproxy.crt:/usr/local/share/ca-certificates/httpproxy.crt
    environment:
      http_proxy:
      https_proxy:
  web:
    image: nginx:alpine
    volumes:
      - ./_site:/usr/share/nginx/html:ro
    ports:
      - 80:80